export const PLANS = {
  basic: {
    id: 'basic',
    name: 'Basic',
    price_inr: 0,
    price_display: '₹0',
    billing: null,
    badge: 'Start Free',
    features: [
      'Medicine & banned drug search (unlimited)',
      '3 free scans/month (75-80% accuracy)',
      'Reminders: up to 3 medicines',
      '2 comparisons/day',
      'Generic finder (unlimited)',
    ],
    not_included: [
      'Handwritten prescription support',
      'Unlimited scans & reminders',
      'Family sharing',
      'PDF downloads',
    ],
    cta: 'Get Started',
    highlight: false,
    scans_label: 'Printed text only',
  },
  family: {
    id: 'family',
    name: 'Family Plan',
    price_inr: 79,
    price_display: '₹79',
    price_strikethrough: '₹99',
    billing: 'per month',
    badge: 'Most Popular',
    features: [
      'Everything in Basic',
      'Unlimited scans (99% accuracy)',
      'Reads handwriting + lab reports',
      'Unlimited reminders + family members',
      'Priority support',
      'Download scan results as PDF',
      'No ads ever',
    ],
    not_included: [
      'Monthly expense reports',
      'Early access to new features',
    ],
    cta: 'Get Family Pro',
    highlight: true,
    scans_label: '99% Accurate Scanner',
    savings_percent: 'Save 20%',
  },
  annual: {
    id: 'annual',
    name: 'Family Annual',
    price_inr: 849,
    price_display: '₹849',
    billing: 'per year',
    badge: 'Best Value',
    features: [
      'Everything in Family Plan',
      'Covers up to 5 family members',
      '₹70.75/month effective price',
      'Medicine expense tracker (monthly report)',
      'Early access to new features',
      'Priority setup for family',
    ],
    not_included: [],
    cta: 'Get Annual Value',
    highlight: false,
    scans_label: 'Best for Families',
    savings_amount: 'Save ₹278 vs monthly',
  },
} as const;

export type PlanId = keyof typeof PLANS;
export type Plan = typeof PLANS[PlanId];
