export const PLANS = {
  basic: {
    id: 'basic',
    name: 'Basic',
    price_inr: 0,
    price_display: '₹0',
    billing: null,
    badge: 'Start Free',
    features: [
      'Medicine & banned drug search (unlimited)',
      '3 free scans/month (75-80% accuracy)',
      'Reminders: up to 3 medicines',
      '2 comparisons/day',
      'Generic finder (unlimited)',
    ],
    not_included: [
      'Handwritten prescription support',
      'Unlimited scans & reminders',
      'Family members (up to 5)',
      'Medication history',
      'Monthly PDF reports',
      'Early access to new features',
    ],
    cta: 'Get Started',
    highlight: false,
    scans_label: 'Printed text only',
  },
  premium: {
    id: 'premium',
    name: 'Premium',
    price_inr: 99,
    price_display: '₹99',
    price_strikethrough: '₹199',
    billing: 'per month',
    badge: 'MOST POPULAR',
    features: [
      'Everything in Basic',
      'Unlimited scans (99% accuracy)',
      'Reads handwriting + lab reports',
      'Unlimited reminders',
      'Family members (up to 5)',
      'Comprehensive medication history',
      'Monthly expense reports (PDF)',
      'Early access to new features',
      'Priority support',
      'No ads ever',
    ],
    not_included: [],
    cta: 'Get Premium',
    highlight: true,
    scans_label: '99% Accurate Scanner',
    savings_percent: 'Save 50%',
  },
} as const;

export type PlanId = keyof typeof PLANS;
export type Plan = typeof PLANS[PlanId];
