import React, { createContext, useContext, useState, useEffect } from 'react';
import { Language } from './types';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    appName: 'Aethelcare',
    tagline: 'Search any medicine. Understand it instantly.',
    searchPlaceholder: 'Search for medicine information...',
    disclaimer: 'This platform provides general medicine information. Always consult a qualified doctor before taking any medication.',
    safetyWarning: 'If symptoms persist for more than 3 days, consult a doctor.',
    uses: 'Uses',
    howItWorks: 'How it works',
    dosage: 'Dosage Guidelines',
    sideEffects: 'Side Effects',
    overdose: 'Overdose Risks',
    warnings: 'Warnings',
    category: 'Drug Category',
    popularMedicines: 'Popular Medicines',
    commonConditions: 'Common Conditions',
    browseByCondition: 'Browse medication information by condition',
    quickHealthAccess: 'Quick access to common health needs',
    viewDetails: 'View Details',
    noBannedFound: 'No matching banned drugs found in our quick lookup.',
    doloSummary: "India's most trusted medicine for fever and body pain relief.",
    augmentinSummary: "Powerful broad-spectrum antibiotic for various bacterial infections.",
    okacetSummary: "Quick relief from allergies, sneezing, and skin itching.",
    pan40Summary: "Effective long-lasting relief from acidity and heartburn.",
    suggestedFever: 'Fever',
    suggestedHeadache: 'Headache',
    suggestedColdCough: 'Cold & cough',
    suggestedComparison: 'Paracetamol vs Ibuprofen',
    doloSearchReason: 'Commonly searched for fever management',
    ibuprofenSearchReason: 'Important safety information for pain relief',
    dryCoughSearchReason: 'Seasonal ailment query',
    throatInfectionSearchReason: 'Frequent bacterial infection query',
    diabetesSearchReason: 'Top searched for diabetes management',
    amlodipineSearchReason: 'Common blood pressure medication query',
    loading: 'Fetching information...',
    category_analgesic: 'Analgesic',
    category_antibiotic: 'Antibiotic',
    category_antihistamine: 'Antihistamine',
    category_antacid: 'Antacid',
    scannerTitle: 'AI Health Scanner',
    scannerSubtitle: 'Scan medicines, doctor prescriptions, or lab reports for instant analysis.',
    medicineMode: 'Medicine',
    prescriptionMode: 'Prescription',
    reportMode: 'Lab Report',
    takePhoto: 'Take Photo',
    uploadImage: 'Upload Image',
    analyzingMedication: 'Analyzing medication...',
    readingPrescription: 'Reading prescription...',
    analyzingReport: 'Analyzing lab report...',
    scannerTips: 'Scanning Tips',
    scannerTip1: 'Ensure the text is clearly visible and in focus',
    scannerTip2: 'Avoid glare or reflections on the paper/packaging',
    scannerTip3: 'Hold the camera steady and use good lighting',
    scannerTip4: 'Make sure the entire document is within the frame',
    scannerTip5: 'For handwritten notes, ensure they are legible',
    confidence: 'Confidence',
    verified: 'Verified',
    viewFullDetails: 'View Full Details',
    prescriptionDetails: 'Prescription Details',
    doctorNotes: "Doctor's Notes",
    abnormalFindings: 'Abnormal Findings',
    noAbnormalFindings: 'No abnormal findings detected in this report.',
    timetableTitle: 'My Timetable',
    timetableSubtitle: 'Manage your daily medication schedule',
    notificationsActive: 'Notifications active',
    addMed: 'Add Med',
    saveSchedule: 'Save Schedule',
    cancel: 'Cancel',
    medicineName: 'Medicine Name',
    medicineSearchPlaceholder: 'Search or type name...',
    dosageLabel: 'Dosage',
    dosagePlaceholder: 'e.g. 1 Tablet',
    timeLabel: 'Time',
    frequencyLabel: 'Frequency',
    todaysDoses: "Today's Doses",
    otherDays: 'Other Days',
    timetableEmpty: 'Your timetable is empty',
    timetableEmptyDesc: 'Add your first medication to stay on track.',
    markAsTaken: 'Mark as Taken',
    taken: 'Taken',
    bannedWarning: 'is a BANNED drug in India. Please consult a doctor immediately.',
    tip1: 'Drink a glass of water with your medicine.',
    tip2: 'Take your medicine at the same time every day.',
    tip3: "Don't skip doses for better effectiveness.",
    tip4: 'Keep medicines in a cool, dry place.',
    tip5: 'Check the expiry date before taking.',
    tip6: 'Avoid taking medicine with fruit juices unless advised.',
    noResults: 'No medicines found.',
    timetable_timing: 'Timing',
    timetable_duration: 'Duration',
    timetable_purpose: 'Purpose',
    backOnline: 'Back Online!',
    allFeaturesAvailable: 'All features are now available.',
    footerCopyright: 'Aethelcare. All rights reserved.',
    privacyPolicy: 'Privacy Policy',
    cdscoOfficial: 'CDSCO Official',
    educationalDisclaimer: 'Educational purposes only. Not a substitute for professional medical advice.',
    installTitle: 'Install Aethelcare',
    installOffline: 'Offline access anywhere',
    installFaster: 'Faster loading times',
    installNow: 'Install Now',
    enableNotificationsPrompt: 'Enable notifications to get medication reminders!',
    notificationsNotSupported: 'Notifications not supported in this browser',
    notificationsBlocked: 'Notifications are blocked. Please enable them in your browser settings.',
    notificationsEnabled: 'Notifications enabled!',
    notificationsReadyDesc: "You'll now receive timely medication reminders and health tips.",
    enableNotifications: 'Enable Notifications',
    timetableLoadError: 'Could not load timetable.',
    scheduleAdded: 'Schedule added successfully',
    scheduleAddError: 'Failed to add schedule',
    scheduleRemoved: 'Schedule removed',
    scheduleRemoveError: 'Failed to remove schedule',
    markedNotTaken: 'Marked as not taken',
    markedTaken: 'Marked as taken! Good job.',
    statusUpdateError: 'Failed to update status',
    timeFor: 'Time for',
    snooze: 'Snooze',
    enabled: 'Enabled',
    day_mon: 'Mon',
    day_tue: 'Tue',
    day_wed: 'Wed',
    day_thu: 'Thu',
    day_fri: 'Fri',
    day_sat: 'Sat',
    day_sun: 'Sun',
    noMedicationFound: 'Could not identify a medication in this image. Please try again with a clearer picture.',
    noPrescriptionFound: 'Could not extract prescription details. Please ensure the image is clear and contains a valid prescription.',
    noReportFound: 'Could not extract lab report details. Please ensure the image is clear and contains a valid medical test report.',
    scanningFailed: 'Scanning failed',
    tryAgain: 'Please try again',
    lowConfidenceWarn: 'Low confidence identification. This image is very difficult to read. Please try again with better lighting or a clearer angle.',
    uncertainIdentification: 'The identification is uncertain due to image quality. Please verify with the physical packaging.',
    result: 'Result',
    normal: 'Normal',
    addedToCompare: 'Added to comparison',
    removedFromCompare: 'Removed from comparison',
    singleLineSummary: 'Summary',
    compare: 'Compare',
    myDashboard: 'My Dashboard',
    dashboardDesc: 'Manage your account, active plans, and payment history.',
    profile: 'Profile',
    role: 'Role',
    joined: 'Joined',
    currentPlan: 'Current Plan',
    active: 'Active',
    expired: 'Expired',
    freeTier: 'Free Tier',
    validUntil: 'Valid Until',
    daysRemaining: 'Days Remaining',
    days: 'Days',
    changePlan: 'Change Plan',
    subscriptionExpired: 'Your Subscription Has Expired',
    subscriptionExpiredDesc: 'Your previous {tier} plan expired on {date}. Renew now to regain access to unlimited AI health scanning and priority support.',
    renewSubscription: 'Renew Subscription',
    noActiveSubscription: 'No Active Subscription',
    noActiveSubscriptionDesc: 'Upgrade to Premium to unlock unlimited AI health scanning, prescription analysis, and lab report insights.',
    upgradeToPremium: 'Upgrade to Premium',
    paymentHistory: 'Payment History',
    loadingHistory: 'Loading payment history...',
    date: 'Date',
    amount: 'Amount',
    status: 'Status',
    transactionId: 'Transaction ID',
    noPayments: 'No payments yet',
    noPaymentsDesc: 'Your payment history will appear here once you subscribe.',
    unlockAIScanner: 'Unlock AI Health Scanner',
    chooseAPlan: 'Choose a plan to access unlimited scanning features',
    mostPopular: 'Most Popular',
    oneTimePass: 'One-Time Pass',
    day: 'day',
    monthlyPro: 'Monthly Pro',
    month: 'month',
    yearlyPremium: 'Yearly Premium',
    year: 'year',
    breakdown: 'Payment Breakdown',
    platformFee: 'Platform Fee',
    gst: 'GST',
    totalAmount: 'Total Amount',
    paySecurely: 'Pay ₹{total} Securely',
    processing: 'Processing...',
    securedByRazorpay: 'Secured by Razorpay',
    oneTimePassDesc: '24 hours of unlimited scanning',
    monthlyProDesc: 'Perfect for regular health monitoring',
    yearlyPremiumDesc: 'Best value for long-term care',
    unlimitedScanning: 'Unlimited AI Scanning',
    prescriptionAnalysis: 'Prescription Analysis',
    labReportAnalysis: 'Lab Report Analysis',
    valid24Hours: 'Valid for 24 hours',
    prioritySupport: 'Priority Support',
    earlyAccess: 'Early Access to Features',
    bannedDrugsRegistry: 'Banned Drugs Registry',
    officialCDSCOData: 'Official CDSCO Data',
    bannedDrugsDesc: 'A comprehensive list of medications prohibited for manufacture and sale in India under Section 26A of the Drugs & Cosmetics Act, 1940.',
    searchBannedPlaceholderLong: 'Search banned drugs by name or side effect...',
    primaryRisk: 'Primary Risk',
    noBannedFoundTitle: 'No banned drugs found',
    noBannedFoundDesc: 'Try adjusting your search terms.',
    vs: 'vs',
    feature: 'Feature',
    difference: 'Difference',
    peopleAlsoSearch: 'People also search for',
    suggestedQueries: 'Suggested queries',
    voiceSearch: 'Voice Search',
    listening: 'Listening...',
    offlineTitle: 'You are offline',
    offlineStatus: 'Showing saved data only',
    offlineLimit: 'AI-powered search and dynamic details are limited.',
    offlineAction: 'Refresh the page once you are back online to re-enable all features.',
    refresh: 'Refresh',
    fever: 'Fever',
    cold: 'Cold & Cough',
    headache: 'Headache',
    diabetes: 'Diabetes',
    hypertension: 'Hypertension',
    acidity: 'Acidity',
    allergies: 'Allergies',
    infections: 'Infections',
    asthma: 'Asthma',
    joint_pain: 'Joint Pain',
    skin_issues: 'Skin Issues',
    eye_strain: 'Eye Strain',
    fatigue: 'Fatigue',
    heart_health: 'Heart Health',
    stomach_flu: 'Stomach Flu',
    back_pain: 'Back Pain',
    migraine: 'Migraine',
    thyroid: 'Thyroid',
    anxiety: 'Anxiety',
    sleep_disturbances: 'Sleep Issues',
    viewAll: 'View All',
    share: 'Share',
    medicalIntelligence: "India's Medical Intelligence",
    privacyFirst: 'Privacy First',
    healthDecoded: 'Your Health,',
    decoded: 'Decoded.',
    heroDescription: 'The most reliable, privacy-centric pharmaceutical intelligence platform for India.',
    diagnosticVision: 'AI Diagnostic Vision',
    diagnosticVisionDesc: 'Identify medications and analyze complex clinical reports with proprietary neural scanning.',
    neuralReminders: 'Neural Reminders',
    neuralRemindersDesc: 'Smart synchronization for your dosage cycles with persistent cross-platform alerts.',
    smartComparison: 'Smart Comparison',
    smartComparisonDesc: 'Side-by-side analysis of salts, side effects, and more.',
    cdscoAlert: 'CDSCO Alert',
    bannedDrugsSearch: 'Banned Drugs Search',
    bannedDrugsSearchDesc: 'Quickly check if a medication is prohibited for manufacture and sale in India.',
    fullRegistry: 'Full Registry',
    medicalDisclaimer: 'Medical Disclaimer',
    launchScanner: 'Launch Scanner',
    authRequired: 'Authentication Required',
    configureCycles: 'Configure Cycles',
    readWhy: 'Read Why',
    peopleAlsoSearchDesc: 'Based on current health trends and CDSCO guidelines',
    timetable: 'Timetable',
    scan: 'Scan',
    dashboard: 'Dashboard',
    adminPanel: 'Admin Panel',
    signOut: 'Sign Out',
    signIn: 'Sign In',
    cdscoVerified: 'CDSCO Verified',
    searchBannedPlaceholder: 'Search banned drug name...',
    analyzingMedicine: 'Analyzing Medicine',
    gatheringData: 'Gathering comprehensive data, side effects, and safety information...',
    medicineNotFound: 'Medicine not found',
    medicineNotFoundDesc: 'We couldn\'t find information for "{name}". Try searching for a generic name or a popular brand.',
    backToHome: 'Back to Home',
    backToSearch: 'Back to Search',
    viewingOfflineData: 'Viewing Offline Data',
    source: 'Source',
    prescriptionRequired: 'Prescription Required',
    otcNonPrescription: 'OTC / Non-Prescription',
    bannedDrug: 'BANNED DRUG',
    stop: 'Stop',
    listen: 'Listen',
    removeFromCompare: 'Remove from Compare',
    reportIssue: 'Report Issue',
    bannedDrugWarning: 'BANNED DRUG WARNING',
    prohibitedInIndia: 'PROHIBITED FOR MANUFACTURE AND SALE IN INDIA',
    bannedDrugNotice: 'This medication has been banned by the CDSCO (Central Drugs Standard Control Organization) due to severe safety concerns and health risks.',
    doNotConsume: 'DO NOT CONSUME THIS MEDICATION',
    quickSummary: 'Quick Summary',
    regulatoryStatus: 'Regulatory Status',
    safety: 'Safety',
    verifiedInfo: 'Verified Info',
    usesConditions: 'Uses & Conditions',
    mechanismOfAction: 'Mechanism of Action',
    commonDosage: 'Common Dosage',
    howItWorksBody: 'How it works in the body',
    onsetOfAction: 'Onset of Action',
    durationOfEffect: 'Duration of Effect',
    whoShouldTake: 'Who should take',
    whoShouldNotTake: 'Who should NOT take',
    missedDose: 'Missed Dose',
    commonSideEffects: 'Common Side Effects',
    seriousSideEffects: 'Serious Side Effects',
    pregnancySafety: 'Pregnancy Safety',
    kidneyLiverWarning: 'Kidney & Liver Warning',
    drugInteractions: 'Drug Interactions',
    foodInteractions: 'Food Interactions',
    alcoholWarning: 'Alcohol Warning',
    overdoseEffects: 'Overdose Effects',
    contraindications: 'Contraindications',
    linkCopied: 'Link copied to clipboard!',
    linkCopyFailed: 'Failed to copy link.',
    featureComparison: 'Side-by-side comparison of features and effects',
    otc: 'OTC',
    conditionNotFound: 'Condition not found',
    conditionNotFoundDesc: "We couldn't find information for this condition. Try searching for a common symptom or disease.",
    comparisonUnavailable: 'Offline: Comparison Unavailable',
    comparisonNotFound: 'Comparison data not found',
    comparisonOfflineDesc: "You're currently offline and this comparison hasn't been cached yet. Please connect to the internet to view this comparison.",
    comparisonNotFoundDesc: "We couldn't find or generate comparison data for these medicines. Please try again later.",
  },
  hi: {
    appName: 'एथेलकेयर',
    tagline: 'किसी भी दवा को खोजें। उसे तुरंत समझें।',
    searchPlaceholder: 'दवा की जानकारी खोजें...',
    disclaimer: 'यह प्लेटफॉर्म सामान्य दवा की जानकारी प्रदान करता है। कोई भी दवा लेने से पहले हमेशा एक योग्य डॉक्टर से सलाह लें।',
    safetyWarning: 'यदि लक्षण 3 दिनों से अधिक समय तक बने रहते हैं, तो डॉक्टर से परामर्श करें।',
    uses: 'उपयोग',
    howItWorks: 'यह कैसे काम करता है',
    dosage: 'खुराक दिशानिर्देश',
    sideEffects: 'दुष्प्रभाव',
    overdose: 'ओवरडोज के जोखिम',
    warnings: 'चेतावनी',
    category: 'दवा श्रेणी',
    popularMedicines: 'लोकप्रिय दवाएं',
    commonConditions: 'सामान्य स्थितियां',
    browseByCondition: 'स्थिति के अनुसार दवा की जानकारी खोजें',
    quickHealthAccess: 'सामान्य स्वास्थ्य आवश्यकताओं तक त्वरित पहुंच',
    viewDetails: 'विवरण देखें',
    noBannedFound: 'हमारी त्वरित खोज में कोई मिलान वाली प्रतिबंधित दवाएं नहीं मिलीं।',
    doloSummary: "बुखार और बदन दर्द से राहत के लिए भारत की सबसे भरोसेमंद दवा।",
    augmentinSummary: "विभिन्न जीवाणु संक्रमणों के लिए शक्तिशाली ब्रॉड-स्पेक्ट्रम एंटीबायोटिक।",
    okacetSummary: "एलर्जी, छींकने और त्वचा की खुजली से त्वरित राहत।",
    pan40Summary: "एसिडिटी और सीने में जलन से प्रभावी लंबे समय तक राहत।",
    suggestedFever: 'बुखार',
    suggestedHeadache: 'सिरदर्द',
    suggestedColdCough: 'सर्दी और खांसी',
    suggestedComparison: 'पैरासिटामोल बनाम इबुप्रोफेन',
    doloSearchReason: 'आमतौर पर बुखार प्रबंधन के लिए खोजा जाता है',
    ibuprofenSearchReason: 'दर्द से राहत के लिए महत्वपूर्ण सुरक्षा जानकारी',
    dryCoughSearchReason: 'मौसमी बीमारी से जुड़ा सवाल',
    throatInfectionSearchReason: 'बार-बार होने वाले जीवाणु संक्रमण से जुड़ा सवाल',
    diabetesSearchReason: 'मधुमेह प्रबंधन के लिए सबसे ज्यादा खोजा गया',
    amlodipineSearchReason: 'सामान्य रक्तचाप दवा से जुड़ा सवाल',
    loading: 'जानकारी प्राप्त की जा रही है...',
    category_analgesic: 'दर्द निवारक',
    category_antibiotic: 'एंटीबायोटिक',
    category_antihistamine: 'एंटीहिस्टामाइन',
    category_antacid: 'एंटासिड',
    scannerTitle: 'एआई स्वास्थ्य स्कैनर',
    scannerSubtitle: 'तत्काल विश्लेषण के लिए दवाओं, डॉक्टर के नुस्खे, या लैब रिपोर्ट को स्कैन करें।',
    medicineMode: 'दवा',
    prescriptionMode: 'नुस्खा',
    reportMode: 'लैब रिपोर्ट',
    takePhoto: 'फोटो लें',
    uploadImage: 'छवि अपलोड करें',
    analyzingMedication: 'दवा का विश्लेषण किया जा रहा है...',
    readingPrescription: 'नुस्खा पढ़ा जा रहा है...',
    analyzingReport: 'लैब रिपोर्ट का विश्लेषण किया जा रहा है...',
    scannerTips: 'स्कैनिंग टिप्स',
    scannerTip1: 'सुनिश्चित करें कि टेक्स्ट स्पष्ट रूप से दिखाई दे रहा है और फोकस में है',
    scannerTip2: 'कागज/पैकेजिंग पर चमक या प्रतिबिंब से बचें',
    scannerTip3: 'कैमरे को स्थिर रखें और अच्छी रोशनी का उपयोग करें',
    scannerTip4: 'सुनिश्चित करें कि पूरा दस्तावेज़ फ्रेम के भीतर है',
    scannerTip5: 'हस्तलिखित नोटों के लिए, सुनिश्चित करें कि वे सुपाठ्य हैं',
    confidence: 'आत्मविश्वास',
    verified: 'सत्यापित',
    viewFullDetails: 'पूर्ण विवरण देखें',
    prescriptionDetails: 'नुस्खे का विवरण',
    doctorNotes: "डॉक्टर के नोट्स",
    abnormalFindings: 'असामान्य निष्कर्ष',
    noAbnormalFindings: 'इस रिपोर्ट में कोई असामान्य निष्कर्ष नहीं मिला।',
    timetableTitle: 'मेरी समय-सारणी',
    timetableSubtitle: 'अपनी दैनिक दवा अनुसूची प्रबंधित करें',
    notificationsActive: 'सूचनाएं सक्रिय हैं',
    addMed: 'दवा जोड़ें',
    saveSchedule: 'शेड्यूल सहेजें',
    cancel: 'रद्द करें',
    medicineName: 'दवा का नाम',
    medicineSearchPlaceholder: 'खोजें या नाम टाइप करें...',
    dosageLabel: 'खुराक',
    dosagePlaceholder: 'जैसे 1 गोली',
    timeLabel: 'समय',
    frequencyLabel: 'आवृत्ति',
    todaysDoses: "आज की खुराक",
    otherDays: 'अन्य दिन',
    timetableEmpty: 'आपकी समय-सारणी खाली है',
    timetableEmptyDesc: 'ट्रैक पर रहने के लिए अपनी पहली दवा जोड़ें।',
    markAsTaken: 'लिया गया के रूप में चिह्नित करें',
    taken: 'ले लिया',
    bannedWarning: 'भारत में एक प्रतिबंधित दवा है। कृपया तुरंत डॉक्टर से परामर्श लें।',
    tip1: 'अपनी दवा के साथ एक गिलास पानी पिएं।',
    tip2: 'हर दिन एक ही समय पर अपनी दवा लें।',
    tip3: "बेहतर प्रभावशीलता के लिए खुराक न छोड़ें।",
    tip4: 'दवाओं को ठंडी, सूखी जगह पर रखें।',
    tip5: 'लेने से पहले समाप्ति तिथि की जांच करें।',
    tip6: 'जब तक सलाह न दी जाए, फलों के रस के साथ दवा लेने से बचें।',
    noResults: 'कोई दवा नहीं मिली।',
    timetable_timing: 'समय',
    timetable_duration: 'अवधि',
    timetable_purpose: 'उद्देश्य',
    backOnline: 'वापस ऑनलाइन!',
    allFeaturesAvailable: 'सभी सुविधाएं अब उपलब्ध हैं।',
    footerCopyright: 'ऐथेलकेयर। सर्वाधिकार सुरक्षित।',
    privacyPolicy: 'गोपनीयता नीति',
    cdscoOfficial: 'सीडीएससीओ आधिकारिक',
    educationalDisclaimer: 'केवल शैक्षिक उद्देश्य के लिए। पेशेवर चिकित्सा सलाह का विकल्प नहीं।',
    installTitle: 'ऐथेलकेयर स्थापित करें',
    installOffline: 'कहीं भी ऑफ़लाइन पहुंच',
    installFaster: 'तेजी से लोडिंग समय',
    installNow: 'अभी स्थापित करें',
    enableNotificationsPrompt: 'दवा अनुस्मारक प्राप्त करने के लिए सूचनाएं सक्षम करें!',
    notificationsNotSupported: 'इस ब्राउज़र में सूचनाएं समर्थित नहीं हैं',
    notificationsBlocked: 'सूचनाएं अवरुद्ध हैं। कृपया अपनी ब्राउज़र सेटिंग्स में उन्हें सक्षम करें।',
    notificationsEnabled: 'सूचनाएं सक्षम!',
    notificationsReadyDesc: 'अब आपको समय पर दवा के रिमाइंडर और स्वास्थ्य सुझाव मिलेंगे।',
    enableNotifications: 'सूचनाएं सक्षम करें',
    timetableLoadError: 'समय-सारणी लोड नहीं की जा सकी।',
    scheduleAdded: 'शेड्यूल सफलतापूर्वक जोड़ा गया',
    scheduleAddError: 'शेड्यूल जोड़ने में विफल',
    scheduleRemoved: 'शेड्यूल हटाया गया',
    scheduleRemoveError: 'शेड्यूल हटाने में विफल',
    markedNotTaken: 'नहीं लिया गया के रूप में चिह्नित',
    markedTaken: 'लिया गया के रूप में चिह्नित! अच्छा काम।',
    statusUpdateError: 'स्थिति अपडेट करने में विफल',
    timeFor: 'समय है',
    snooze: 'स्नूज़',
    enabled: 'सक्षम',
    day_mon: 'सोम',
    day_tue: 'मंगल',
    day_wed: 'बुध',
    day_thu: 'गुरु',
    day_fri: 'शुक्र',
    day_sat: 'शनि',
    day_sun: 'रवि',
    noMedicationFound: 'इस छवि में दवा की पहचान नहीं हो सकी। कृपया स्पष्ट चित्र के साथ पुनः प्रयास करें।',
    noPrescriptionFound: 'प्रिस्क्रिप्शन विवरण नहीं निकाला जा सका। कृपया सुनिश्चित करें कि छवि स्पष्ट है और इसमें वैध नुस्खा है।',
    noReportFound: 'लैब रिपोर्ट विवरण नहीं निकाला जा सका। कृपया सुनिश्चित करें कि छवि स्पष्ट है और इसमें वैध मेडिकल रिपोर्ट है।',
    scanningFailed: 'स्कैनिंग विफल रही',
    tryAgain: 'कृपया पुनः प्रयास करें',
    lowConfidenceWarn: 'कम आत्मविश्वास वाली पहचान। यह तस्वीर पढ़ना काफी मुश्किल है। कृपया बेहतर रोशनी या स्पष्ट कोण के साथ फिर से प्रयास करें।',
    uncertainIdentification: 'छवि गुणवत्ता के कारण पहचान अनिश्चित है। कृपया उत्पाद की पैकेजिंग से सत्यापन करें।',
    result: 'परिणाम',
    normal: 'सामान्य',
    addedToCompare: 'तुलना में जोड़ा गया',
    removedFromCompare: 'तुलना से हटाया गया',
    singleLineSummary: 'सारांश',
    compare: 'तुलना करें',
    myDashboard: 'मेरा डैशबोर्ड',
    dashboardDesc: 'अपने खाते, सक्रिय योजनाओं और भुगतान इतिहास को प्रबंधित करें।',
    profile: 'प्रोफ़ाइल',
    role: 'भूमिका',
    joined: 'शामिल हुए',
    currentPlan: 'वर्तमान योजना',
    active: 'सक्रिय',
    expired: 'समाप्त',
    freeTier: 'फ्री टियर',
    validUntil: 'तक मान्य',
    daysRemaining: 'शेष दिन',
    days: 'दिन',
    changePlan: 'योजना बदलें',
    subscriptionExpired: 'आपकी सदस्यता समाप्त हो गई है',
    subscriptionExpiredDesc: 'आपकी पिछली {tier} योजना {date} को समाप्त हो गई थी। असीमित एआई स्वास्थ्य स्कैनिंग और प्राथमिकता सहायता तक फिर से पहुंच प्राप्त करने के लिए अभी नवीनीकृत करें।',
    renewSubscription: 'सदस्यता नवीनीकृत करें',
    noActiveSubscription: 'कोई सक्रिय सदस्यता नहीं',
    noActiveSubscriptionDesc: 'असीमित एआई स्वास्थ्य स्कैनिंग, प्रिस्क्रिप्शन विश्लेषण और लैब रिपोर्ट अंतर्दृष्टि अनलॉक करने के लिए प्रीमियम में अपग्रेड करें।',
    upgradeToPremium: 'प्रीमियम में अपग्रेड करें',
    paymentHistory: 'भुगतान इतिहास',
    loadingHistory: 'भुगतान इतिहास लोड हो रहा है...',
    date: 'तिथि',
    amount: 'राशि',
    status: 'स्थिति',
    transactionId: 'लेनदेन आईडी',
    noPayments: 'अभी तक कोई भुगतान नहीं',
    noPaymentsDesc: 'एक बार सदस्यता लेने के बाद आपका भुगतान इतिहास यहां दिखाई देगा।',
    unlockAIScanner: 'एआई हेल्थ स्कैनर अनलॉक करें',
    chooseAPlan: 'असीमित स्कैनिंग सुविधाओं का आनंद लेने के लिए एक योजना चुनें',
    mostPopular: 'सबसे लोकप्रिय',
    oneTimePass: 'वन-टाइम पास',
    day: 'दिन',
    monthlyPro: 'मंथली प्रो',
    month: 'महीना',
    yearlyPremium: 'इयरली प्रीमियम',
    year: 'वर्ष',
    breakdown: 'भुगतान विवरण',
    platformFee: 'प्लेटफ़ॉर्म शुल्क',
    gst: 'जीएसटी',
    totalAmount: 'कुल राशि',
    paySecurely: 'सुरक्षित रूप से ₹{total} का भुगतान करें',
    processing: 'प्रसंस्करण...',
    securedByRazorpay: 'रेजरपे द्वारा सुरक्षित',
    oneTimePassDesc: '24 घंटे असीमित स्कैनिंग',
    monthlyProDesc: 'नियमित स्वास्थ्य निगरानी के लिए उपयुक्त',
    yearlyPremiumDesc: 'दीर्घकालिक देखभाल के लिए सर्वोत्तम मूल्य',
    unlimitedScanning: 'असीमित एआई स्कैनिंग',
    prescriptionAnalysis: 'प्रिस्क्रिप्शन विश्लेषण',
    labReportAnalysis: 'लैब रिपोर्ट विश्लेषण',
    valid24Hours: '24 घंटे के लिए मान्य',
    prioritySupport: 'प्राथमिकता सहायता',
    earlyAccess: 'सुविधाओं तक शीघ्र पहुंच',
    bannedDrugsRegistry: 'प्रतिबंधित दवाओं की रजिस्ट्री',
    officialCDSCOData: 'आधिकारिक सीडीएससीओ डेटा',
    bannedDrugsDesc: 'ड्रग्स एंड कॉस्मेटिक्स एक्ट, 1940 की धारा 26 ए के तहत भारत में निर्माण और बिक्री के लिए प्रतिबंधित दवाओं की एक व्यापक सूची।',
    searchBannedPlaceholderLong: 'नाम या दुष्प्रभाव के आधार पर प्रतिबंधित दवाएं खोजें...',
    primaryRisk: 'मुख्य जोखिम',
    noBannedFoundTitle: 'कोई प्रतिबंधित दवा नहीं मिली',
    noBannedFoundDesc: 'अपने खोज शब्दों को समायोजित करने का प्रयास करें।',
    vs: 'बनाम',
    feature: 'विशेषता',
    difference: 'अंतर',
    peopleAlsoSearch: 'लोग यह भी खोजते हैं',
    suggestedQueries: 'सुझाए गए प्रश्न',
    voiceSearch: 'वॉयस सर्च',
    listening: 'सुन रहे हैं...',
    offlineTitle: 'आप ऑफलाइन हैं',
    offlineStatus: 'केवल सहेजा गया डेटा दिखा रहा है',
    offlineLimit: 'एआई-संचालित खोज और गतिशील विवरण सीमित हैं।',
    offlineAction: 'सभी सुविधाओं को फिर से सक्षम करने के लिए वापस ऑनलाइन होने पर पेज को रिफ्रेश करें।',
    refresh: 'रिफ्रेश करें',
    fever: 'बुखार',
    cold: 'सर्दी और खांसी',
    headache: 'सिरदर्द',
    diabetes: 'मधुमेह',
    hypertension: 'उच्च रक्तचाप',
    acidity: 'एसिडिटी',
    allergies: 'एलर्जी',
    infections: 'संक्रमण',
    asthma: 'दमा',
    joint_pain: 'जोड़ों का दर्द',
    skin_issues: 'त्वचा की समस्याएं',
    eye_strain: 'आंखों का तनाव',
    fatigue: 'थकान',
    heart_health: 'हृदय स्वास्थ्य',
    stomach_flu: 'पेट फ्लू',
    back_pain: 'पीठ दर्द',
    migraine: 'माइग्रेन',
    thyroid: 'थायराइड',
    anxiety: 'चिंता',
    sleep_disturbances: 'नींद की समस्याएं',
    viewAll: 'सभी देखें',
    share: 'साझा करें',
    medicalIntelligence: 'भारत की मेडिकल इंटेलिजेंस',
    privacyFirst: 'गोपनीयता पहले',
    healthDecoded: 'आपका स्वास्थ्य,',
    decoded: 'डिकोडेड।',
    heroDescription: 'भारत के लिए सबसे विश्वसनीय, गोपनीयता-केंद्रित फार्मास्युटिकल इंटेलिजेंस प्लेटफॉर्म।',
    diagnosticVision: 'एआई डायग्नोस्टिक विजन',
    diagnosticVisionDesc: 'प्रोप्रायटरी न्यूरल स्कैनिंग के साथ दवाओं की पहचान करें और जटिल नैदानिक रिपोर्टों का विश्लेषण करें।',
    neuralReminders: 'न्यूरल रिमाइंडर',
    neuralRemindersDesc: 'लगातार क्रॉस-प्लेटफॉर्म अलर्ट के साथ आपके खुराक चक्रों के लिए स्मार्ट सिंक्रोनाइज़ेशन।',
    smartComparison: 'स्मार्ट तुलना',
    smartComparisonDesc: 'साल्ट, साइड इफेक्ट्स और बहुत कुछ का साइड-बाय-साइड विश्लेषण।',
    cdscoAlert: 'सीडीएससीओ अलर्ट',
    bannedDrugsSearch: 'प्रतिबंधित दवाओं की खोज',
    bannedDrugsSearchDesc: 'जल्दी से जांचें कि क्या भारत में किसी दवा के निर्माण और बिक्री पर प्रतिबंध है।',
    fullRegistry: 'पूर्ण रजिस्ट्री',
    medicalDisclaimer: 'चिकित्सा अस्वीकरण',
    launchScanner: 'स्कैनर लॉन्च करें',
    authRequired: 'प्रमाणीकरण आवश्यक',
    configureCycles: 'चक्र कॉन्फ़िगर करें',
    readWhy: 'क्यों पढ़ें',
    peopleAlsoSearchDesc: 'वर्तमान स्वास्थ्य प्रवृत्तियों और सीडीएससीओ दिशानिर्देशों पर आधारित',
    timetable: 'समय सारिणी',
    scan: 'स्कैन',
    dashboard: 'डैशबोर्ड',
    adminPanel: 'एडमिन पैनल',
    signOut: 'साइन आउट',
    signIn: 'साइन इन',
    cdscoVerified: 'सीडीएससीओ सत्यापित',
    searchBannedPlaceholder: 'प्रतिबंधित दवा का नाम खोजें...',
    analyzingMedicine: 'दवा का विश्लेषण',
    gatheringData: 'व्यापक डेटा, दुष्प्रभाव और सुरक्षा जानकारी एकत्र की जा रही है...',
    medicineNotFound: 'दवा नहीं मिली',
    medicineNotFoundDesc: 'हमें "{name}" के लिए जानकारी नहीं मिल सकी। सामान्य नाम या लोकप्रिय ब्रांड खोजने का प्रयास करें।',
    backToHome: 'होम पर वापस',
    backToSearch: 'खोज पर वापस',
    viewingOfflineData: 'ऑफलाइन डेटा देख रहे हैं',
    source: 'स्रोत',
    prescriptionRequired: 'पर्चे की आवश्यकता',
    otcNonPrescription: 'ओटीसी / बिना पर्चे के',
    bannedDrug: 'प्रतिबंधित दवा',
    stop: 'रुकें',
    listen: 'सुनें',
    removeFromCompare: 'तुलना से निकालें',
    reportIssue: 'समस्या की रिपोर्ट करें',
    bannedDrugWarning: 'प्रतिबंधित दवा की चेतावनी',
    prohibitedInIndia: 'भारत में निर्माण और बिक्री के लिए प्रतिबंधित',
    bannedDrugNotice: 'गंभीर सुरक्षा चिंताओं और स्वास्थ्य जोखिमों के कारण सीडीएससीओ (सेंट्रल ड्रग्स स्टैंडर्ड कंट्रोल ऑर्गनाइजेशन) द्वारा इस दवा पर प्रतिबंध लगा दिया गया है।',
    doNotConsume: 'इस दवा का सेवन न करें',
    quickSummary: 'त्वरित सारांश',
    regulatoryStatus: 'नियामक स्थिति',
    safety: 'सुरक्षा',
    verifiedInfo: 'सत्यापित जानकारी',
    usesConditions: 'उपयोग और स्थितियां',
    mechanismOfAction: 'काम करने का तरीका',
    commonDosage: 'सामान्य खुराक',
    howItWorksBody: 'शरीर में यह कैसे काम करता है',
    onsetOfAction: 'क्रिया की शुरुआत',
    durationOfEffect: 'प्रभाव की अवधि',
    whoShouldTake: 'किसे लेना चाहिए',
    whoShouldNotTake: 'किसे नहीं लेना चाहिए',
    missedDose: 'छूटी हुई खुराक',
    commonSideEffects: 'सामान्य दुष्प्रभाव',
    seriousSideEffects: 'गंभीर दुष्प्रभाव',
    pregnancySafety: 'गर्भावस्था सुरक्षा',
    kidneyLiverWarning: 'गुर्दे और यकृत की चेतावनी',
    drugInteractions: 'दवाओं का परस्पर प्रभाव',
    foodInteractions: 'भोजन के साथ परस्पर प्रभाव',
    alcoholWarning: 'शराब की चेतावनी',
    overdoseEffects: 'ओवरडोज के प्रभाव',
    contraindications: 'मतभेद',
    linkCopied: 'लिंक क्लिपबोर्ड पर कॉपी किया गया!',
    linkCopyFailed: 'लिंक कॉपी करने में विफल।',
    featureComparison: 'विशेषताओं और प्रभावों का साथ-साथ विश्लेषण',
    otc: 'ओटीसी',
    conditionNotFound: 'स्थिति नहीं मिली',
    conditionNotFoundDesc: "हमें इस स्थिति के लिए जानकारी नहीं मिल सकी। सामान्य लक्षण या बीमारी खोजने का प्रयास करें।",
    comparisonUnavailable: 'ऑफलाइन: तुलना उपलब्ध नहीं है',
    comparisonNotFound: 'तुलना डेटा नहीं मिला',
    comparisonOfflineDesc: "आप वर्तमान में ऑफलाइन हैं और यह तुलना अभी तक कैश नहीं की गई है। कृपया इस तुलना को देखने के लिए इंटरनेट से जुड़ें।",
    comparisonNotFoundDesc: "हम इन दवाओं के लिए तुलना डेटा नहीं ढूंढ सके या उत्पन्न नहीं कर सके। कृपया बाद में पुनः प्रयास करें।",
  },
  mr: {
    appName: 'एथेलकेयर',
    tagline: 'कोणतेही औषध शोधा. ते त्वरित समजून घ्या.',
    searchPlaceholder: 'औषधाची माहिती शोधा...',
    disclaimer: 'हे प्लॅटफॉर्म सामान्य औषधांची माहिती प्रदान करते. कोणतेही औषध घेण्यापूर्वी नेहमी तज्ञ डॉक्टरांचा सल्ला घ्या.',
    safetyWarning: 'लक्षणे ३ दिवसांपेक्षा जास्त काळ राहिल्यास डॉक्टरांचा सल्ला घ्या.',
    uses: 'उपयोग',
    howItWorks: 'हे कसे कार्य करते',
    dosage: 'डोस मार्गदर्शक तत्त्वे',
    sideEffects: 'दुष्परिणाम',
    overdose: 'ओव्हरडोजचे धोके',
    warnings: 'इशारे',
    category: 'औषध श्रेणी',
    popularMedicines: 'लोकप्रिय औषधे',
    commonConditions: 'सामान्य आजार',
    browseByCondition: 'आजारांच्या प्रकारानुसार औषधांची माहिती मिळवा',
    quickHealthAccess: 'सामान्य आरोग्य गरजांसाठी त्वरित प्रवेश',
    viewDetails: 'तपशील पहा',
    noBannedFound: 'आमच्या त्वरित शोधामध्ये कोणतीही प्रतिबंधित औषधे सापडली नाहीत.',
    doloSummary: "ताप आणि अंगदुखीपासून आरामासाठी भारतातील सर्वात विश्वसनीय औषध.",
    augmentinSummary: "विविध जिवाणू संसर्गासाठी शक्तिशाली ब्रॉड-स्पेक्ट्रम प्रतिजैविक.",
    okacetSummary: "ऍलर्जी, शिंका येणे आणि त्वचेला खाज सुटण्यापासून त्वरित आराम.",
    pan40Summary: "ऍसिडिटी आणि छातीत जळजळ होण्यापासून प्रभावी दीर्घकाळ आराम.",
    suggestedFever: 'ताप',
    suggestedHeadache: 'डोकेदुखी',
    suggestedColdCough: 'सर्दी आणि खोकला',
    suggestedComparison: 'पॅरासिटामॉल विरुद्ध आयबुप्रोफेन',
    doloSearchReason: 'ताप व्यवस्थापनासाठी सामान्यतः शोधले जाते',
    ibuprofenSearchReason: 'वेदना आरामासाठी महत्त्वाची सुरक्षा माहिती',
    dryCoughSearchReason: 'हंगामी आजाराबद्दल प्रश्न',
    throatInfectionSearchReason: 'वारंवार होणाऱ्या जिवाणू संसर्गाबद्दल माहिती',
    diabetesSearchReason: 'मधुमेह व्यवस्थापनासाठी सर्वाधिक शोधले जाते',
    amlodipineSearchReason: 'रक्तदाब औषधांबद्दल सामान्य प्रश्न',
    loading: 'माहिती मिळवत आहे...',
    category_analgesic: 'वेदनानाशक',
    category_antibiotic: 'प्रतिजैविक',
    category_antihistamine: 'अँटीहिस्टामाइन',
    category_antacid: 'अँटासिड',
    scannerTitle: 'एआय आरोग्य स्कॅनर',
    scannerSubtitle: 'तात्काळ विश्लेषणासाठी औषधे, डॉक्टरांचे प्रिस्क्रिप्शन किंवा लॅब रिपोर्ट्स स्कॅन करा.',
    medicineMode: 'औषध',
    prescriptionMode: 'प्रिस्क्रिप्शन',
    reportMode: 'लॅब रिपोर्ट',
    takePhoto: 'फोटो काढा',
    uploadImage: 'फोटो अपलोड करा',
    analyzingMedication: 'औषधाचे विश्लेषण करत आहे...',
    readingPrescription: 'प्रिस्क्रिप्शन वाचत आहे...',
    analyzingReport: 'लॅब रिपोर्टचे विश्लेषण करत आहे...',
    scannerTips: 'स्कॅनिंग टिप्स',
    scannerTip1: 'मजकूर स्पष्टपणे दृश्यमान आणि फोकसमध्ये असल्याची खात्री करा',
    scannerTip2: 'कागद/पॅकेजिंगवरील चकाकी किंवा प्रतिबिंब टाळा',
    scannerTip3: 'कॅमेरा स्थिर धरा आणि चांगल्या प्रकाशाचा वापर करा',
    scannerTip4: 'संपूर्ण दस्तऐवज फ्रेममध्ये असल्याची खात्री करा',
    scannerTip5: 'हस्तलिखित नोट्स सुवाच्य असल्याची खात्री करा',
    confidence: 'आत्मविश्वास',
    verified: 'सत्यापित',
    viewFullDetails: 'पूर्ण तपशील पहा',
    prescriptionDetails: 'प्रिस्क्रिप्शन तपशील',
    doctorNotes: "डॉक्टरांच्या नोट्स",
    abnormalFindings: 'असामान्य निष्कर्ष',
    noAbnormalFindings: 'या रिपोर्टमध्ये कोणतेही असामान्य निष्कर्ष आढळले नाहीत.',
    timetableTitle: 'माझी वेळापत्रक',
    timetableSubtitle: 'तुमचे दैनंदिन औषध वेळापत्रक व्यवस्थापित करा',
    notificationsActive: 'सूचना सक्रिय आहेत',
    addMed: 'औषध जोडा',
    saveSchedule: 'वेळापत्रक जतन करा',
    cancel: 'रद्द करा',
    medicineName: 'औषधाचे नाव',
    medicineSearchPlaceholder: 'शोधा किंवा नाव टाईप करा...',
    dosageLabel: 'डोस',
    dosagePlaceholder: 'उदा. १ गोळी',
    timeLabel: 'वेळ',
    frequencyLabel: 'वारंवारता',
    todaysDoses: "आजचे डोस",
    otherDays: 'इतर दिवस',
    timetableEmpty: 'तुमची वेळापत्रक रिकामी आहे',
    timetableEmptyDesc: 'ट्रॅकवर राहण्यासाठी तुमचे पहिले औषध जोडा.',
    markAsTaken: 'घेतले म्हणून मार्क करा',
    taken: 'घेतले',
    bannedWarning: 'हे भारतात प्रतिबंधित औषध आहे. कृपया त्वरित डॉक्टरांशी संपर्क साधा.',
    tip1: 'तुमच्या औषधासोबत ग्लासभर पाणी प्या.',
    tip2: 'दररोज एकाच वेळी औषध घ्या.',
    tip3: "चांगल्या परिणामकारकतेसाठी डोस चुकवू नका.",
    tip4: 'औषधे थंड, कोरड्या जागी ठेवा.',
    tip5: 'घेण्यापूर्वी एक्सपायरी डेट तपासा.',
    tip6: 'सल्ला दिल्याशिवाय फळांच्या रसासोबत औषध घेणे टाळा।',
    noResults: 'कोणतेही औषध सापडले नाही।',
    timetable_timing: 'वेळ',
    timetable_duration: 'कालावधी',
    timetable_purpose: 'हेतू',
    backOnline: 'पुन्हा ऑनलाइन!',
    allFeaturesAvailable: 'सर्व वैशिष्ट्ये आता उपलब्ध आहेत।',
    footerCopyright: 'ऐथेलकेअर। सर्व हक्क राखीव।',
    privacyPolicy: 'गोपनीयता धोरण',
    cdscoOfficial: 'सीडीएससीओ अधिकृत',
    educationalDisclaimer: 'केवळ शैक्षणिक हेतूसाठी। व्यावसायिक वैद्यकीय सल्ल्याचा पर्याय नाही।',
    installTitle: 'ऐथेलकेअर स्थापित करा',
    installOffline: 'कुठेही ऑफलाइन प्रवेश',
    installFaster: 'वेगवान लोडिंग वेळ',
    installNow: 'आता स्थापित करा',
    enableNotificationsPrompt: 'औषध स्मरणपत्रे मिळविण्यासाठी सूचना सक्षम करा!',
    notificationsNotSupported: 'या ब्राउझरमध्ये सूचना समर्थित नाहीत',
    notificationsBlocked: 'सूचना ब्लॉक केल्या आहेत। कृपया तुमच्या ब्राउझर सेटिंग्जमध्ये त्या सक्षम करा।',
    notificationsEnabled: 'सूचना सक्षम केल्या!',
    notificationsReadyDesc: 'तुम्हाला आता वेळेवर औषध स्मरणपत्रे आणि आरोग्य टिप्स मिळतील।',
    enableNotifications: 'सूचना सक्षम करा',
    timetableLoadError: 'वेळापत्रक लोड होऊ शकले नाही।',
    scheduleAdded: 'वेळापत्रक यशस्वीपणे जोडले गेले',
    scheduleAddError: 'वेळापत्रक जोडण्यात अपयशी',
    scheduleRemoved: 'वेळापत्रक काढून टाकले',
    scheduleRemoveError: 'वेळापत्रक काढण्यात अपयशी',
    markedNotTaken: 'घेतले नाही म्हणून नोंदवले',
    markedTaken: 'घेतले म्हणून नोंदवले! छान।',
    statusUpdateError: 'स्थिती अपडेट करण्यात अपयशी',
    timeFor: 'वेळ झाली आहे',
    snooze: 'स्र्नुझ (Snooze)',
    enabled: 'सक्षम',
    day_mon: 'सोम',
    day_tue: 'मंळ',
    day_wed: 'बुध',
    day_thu: 'गुरू',
    day_fri: 'शुक्र',
    day_sat: 'शनी',
    day_sun: 'रवी',
    noMedicationFound: 'या प्रतिमेमध्ये औषध ओळखता आले नाही। कृपया स्पष्ट फोटोसह पुन्हा प्रयत्न करा।',
    noPrescriptionFound: 'प्रिस्क्रिप्शन तपशील काढता आले नाहीत। कृपया फोटो स्पष्ट असल्याची आणि त्यात वैध प्रिस्क्रिप्शन असल्याची खात्री करा।',
    noReportFound: 'लॅब रिपोर्ट तपशील काढता आले नाहीत। कृपया फोटो स्पष्ट असल्याची आणि त्यात वैध मेडिकल रिपोर्ट असल्याची खात्री करा।',
    scanningFailed: 'स्कॅनिंग अयशस्वी',
    tryAgain: 'कृपया पुन्हा प्रयत्न करा',
    lowConfidenceWarn: 'ओळख पटवताना कमी आत्मविश्वास। ही इमेज वाचणे कठीण आहे। कृपया चांगल्या प्रकाशात किंवा स्पष्ट कोनातून प्रयत्न करा।',
    uncertainIdentification: 'इमेजच्या दर्जा मुळे ओळख अनिश्चित आहे। कृपया उत्पादनाच्या पॅकिंगवरून पडताळणी करा।',
    result: 'निकाल',
    normal: 'सामान्य',
    addedToCompare: 'तुलनेमध्ये जोडले',
    removedFromCompare: 'तुलनेतून काढले',
    singleLineSummary: 'सारांश',
    compare: 'तुलना करा',
    myDashboard: 'माझा डॅशबोर्ड',
    dashboardDesc: 'तुमचे खाते, सक्रिय योजना आणि पेमेंट इतिहास व्यवस्थापित करा.',
    profile: 'प्रोफाइल',
    role: 'भूमिका',
    joined: 'सामील झाले',
    currentPlan: 'वर्तमान योजना',
    active: 'सक्रिय',
    expired: 'कालबाह्य',
    freeTier: 'विनामूल्य श्रेणी',
    validUntil: 'पर्यंत वैध',
    daysRemaining: 'शिल्लक दिवस',
    days: 'दिवस',
    changePlan: 'योजना बदला',
    subscriptionExpired: 'तुमची सदस्यता कालबाह्य झाली आहे',
    subscriptionExpiredDesc: 'तुमची मागील {tier} योजना {date} रोजी संपली आहे. अमर्यादित एआय आरोग्य स्कॅनिंग आणि प्राधान्य सपोर्ट मिळवण्यासाठी आता रिन्यू करा.',
    renewSubscription: 'सदस्यता रिन्यू करा',
    noActiveSubscription: 'कोणतीही सक्रिय सदस्यता नाही',
    noActiveSubscriptionDesc: 'अमर्यादित एआय आरोग्य स्कॅनिंग, प्रिस्क्रिप्शन विश्लेषण आणि लॅब रिपोर्ट माहितीसाठी प्रीमियममध्ये अपग्रेड करा.',
    upgradeToPremium: 'प्रीमियममध्ये अपग्रेड करा',
    paymentHistory: 'पेमेंट इतिहास',
    loadingHistory: 'पेमेंट इतिहास लोड होत आहे...',
    date: 'दिनांक',
    amount: 'रक्कम',
    status: 'स्थिती',
    transactionId: 'ट्रान्झॅक्शन आयडी',
    noPayments: 'अद्याप कोणतेही पेमेंट नाही',
    noPaymentsDesc: 'तुम्ही सदस्यता घेतल्यावर तुमचा पेमेंट इतिहास येथे दिसेल.',
    unlockAIScanner: 'एआय हेल्थ स्कॅनर अनलॉक करा',
    chooseAPlan: 'अमर्यादित स्कॅनिंग वैशिष्ट्ये वापरण्यासाठी एक योजना निवडा',
    mostPopular: 'सर्वात लोकप्रिय',
    oneTimePass: 'वन-टाइम पास',
    day: 'दिवस',
    monthlyPro: 'मंथली प्रो',
    month: 'महिना',
    yearlyPremium: 'इयरली प्रीमियम',
    year: 'वर्ष',
    breakdown: 'पेमेंट तपशील',
    platformFee: 'प्लॅटफॉर्म फी',
    gst: 'जीएसटी',
    totalAmount: 'एकूण रक्कम',
    paySecurely: 'सुरक्षितपणे ₹{total} पेमेंट करा',
    processing: 'प्रक्रिया सुरू आहे...',
    securedByRazorpay: 'रेझरपे द्वारे सुरक्षित',
    oneTimePassDesc: '24 तास अमर्यादित स्कॅनिंग',
    monthlyProDesc: 'नियमित आरोग्य देखरेखीसाठी योग्य',
    yearlyPremiumDesc: 'दीर्घकालीन काळजीसाठी सर्वोत्तम',
    unlimitedScanning: 'अमर्यादित एआय स्कॅनिंग',
    prescriptionAnalysis: 'प्रिस्क्रिप्शन विश्लेषण',
    labReportAnalysis: 'लॅब रिपोर्ट विश्लेषण',
    valid24Hours: '24 तासांसाठी वैध',
    prioritySupport: 'प्राधान्य सपोर्ट',
    earlyAccess: 'वैशिष्ट्यांमध्ये लवकर प्रवेश',
    bannedDrugsRegistry: 'प्रतिबंधित औषधांची नोंदणी',
    officialCDSCOData: 'अधिकृत सीडीएससीओ डेटा',
    bannedDrugsDesc: 'ड्रग्ज अँड कॉस्मेटिक्स ॲक्ट, १९४० च्या कलम २६ ए अंतर्गत भारतात उत्पादनासाठी आणि विक्रीसाठी प्रतिबंधित असलेल्या औषधांची एक व्यापक यादी।',
    searchBannedPlaceholderLong: 'नाव किंवा दुष्परिणामांनुसार प्रतिबंधित औषधे शोधा...',
    primaryRisk: 'मुख्य जोखीम',
    noBannedFoundTitle: 'कोणतीही प्रतिबंधित औषधे सापडली नाहीत',
    noBannedFoundDesc: 'तुमचे शोध संज्ञा बदलण्याचा प्रयत्न करा।',
    vs: 'विरुद्ध',
    feature: 'वैशिष्ट्य',
    difference: 'फरक',
    peopleAlsoSearch: 'लोक हे देखील शोधतात',
    suggestedQueries: 'सुचवलेले प्रश्न',
    voiceSearch: 'व्हॉइस सर्च',
    listening: 'ऐकत आहे...',
    offlineTitle: 'तुम्ही ऑफलाइन आहात',
    offlineStatus: 'केवळ जतन केलेला डेटा दर्शवित आहे',
    offlineLimit: 'एआय-आधारित शोध आणि डायनॅमिक तपशील मर्यादित आहेत.',
    offlineAction: 'सर्व वैशिष्ट्ये पुन्हा सक्षम करण्यासाठी तुम्ही परत ऑनलाइन आल्यावर पेज रिफ्रेश करा.',
    refresh: 'रिफ्रेश करा',
    fever: 'ताप',
    cold: 'सर्दी आणि खोकला',
    headache: 'डोकेदुखी',
    diabetes: 'मधुमेह',
    hypertension: 'उच्च रक्तदाब',
    acidity: 'ऍसिडिटी',
    allergies: 'अॅलर्जी',
    infections: 'संसर्ग',
    asthma: 'दमा',
    joint_pain: 'सांधेदुखी',
    skin_issues: 'त्वचेच्या समस्या',
    eye_strain: 'डोळ्यांचा ताण',
    fatigue: 'थकवा',
    heart_health: 'हृदय आरोग्य',
    stomach_flu: 'पोटाचा फ्लू',
    back_pain: 'पाठदुखी',
    migraine: 'मायग्रेन',
    thyroid: 'थायरॉईड',
    anxiety: 'चिंता',
    sleep_disturbances: 'झोपेच्या समस्या',
    viewAll: 'सर्व पहा',
    share: 'शेअर करा',
    medicalIntelligence: 'भारताचे मेडिकल इंटेलिजन्स',
    privacyFirst: 'गोपनीयता प्रथम',
    healthDecoded: 'तुमचे आरोग्य,',
    decoded: 'डिकोडेड.',
    heroDescription: 'भारतासाठी सर्वात विश्वसनीय, गोपनीयता-केंद्रित फार्मास्युटिकल इंटेलिजन्स प्लॅटफॉर्म.',
    diagnosticVision: 'एआय डायग्नोस्टिक व्हिजन',
    diagnosticVisionDesc: 'प्रोप्रायटरी न्यूरल स्कॅनिंगसह औषधे ओळखा आणि जटिल क्लिनिकल अहवालांचे विश्लेषण करा.',
    neuralReminders: 'न्यूरल रिमाइंडर्स',
    neuralRemindersDesc: 'सतत क्रॉस-प्लॅटफॉर्म अलर्टसह तुमच्या डोस सायकलसाठी स्मार्ट सिंक्रोनाइझेशन.',
    smartComparison: 'स्मार्ट तुलना',
    smartComparisonDesc: 'साल्ट, साइड इफेक्ट्स आणि अधिकचे side-by-side विश्लेषण.',
    cdscoAlert: 'सीडीएससीओ अलर्ट',
    bannedDrugsSearch: 'प्रतिबंधित औषध शोध',
    bannedDrugsSearchDesc: 'भारतात औषध उत्पादनास आणि विक्रीस बंदी आहे का ते द्रुतपणे तपासा.',
    fullRegistry: 'पूर्ण नोंदणी',
    medicalDisclaimer: 'वैद्यकीय अस्वीकरण',
    launchScanner: 'स्कॅनर सुरू करा',
    authRequired: 'प्रमाणीकरण आवश्यक',
    configureCycles: 'सायकल कॉन्फिगर करा',
    readWhy: 'का ते वाचा',
    peopleAlsoSearchDesc: 'सध्याच्या आरोग्य ट्रेंड आणि सीडीएससीओ मार्गदर्शक तत्त्वांवर आधारित',
    timetable: 'वेळापत्रक',
    scan: 'स्कॅन',
    dashboard: 'डॅशबोर्ड',
    adminPanel: 'अॅडमिन पॅनेल',
    signOut: 'साइन आउट',
    signIn: 'साइन इन',
    cdscoVerified: 'सीडीएससीओ सत्यापित',
    searchBannedPlaceholder: 'प्रतिबंधित औषधाचे नाव शोधा...',
    analyzingMedicine: 'औषधाचे विश्लेषण',
    gatheringData: 'सर्वसमावेशक डेटा, दुष्परिणाम आणि सुरक्षितता माहिती गोळा करत आहे...',
    medicineNotFound: 'औषध सापडले नाही',
    medicineNotFoundDesc: 'आम्हाला "{name}" साठी माहिती सापडली नाही. सामान्य नाव किंवा लोकप्रिय ब्रँड शोधण्याचा प्रयत्न करा.',
    backToHome: 'होमवर परत',
    backToSearch: 'शोधावर परत',
    viewingOfflineData: 'ऑफलाइन डेटा पाहत आहे',
    source: 'स्रोत',
    prescriptionRequired: 'डॉक्टरांच्या चिठ्ठीची गरज',
    otcNonPrescription: 'ओटीसी / प्रिस्क्रिप्शनशिवाय',
    bannedDrug: 'प्रतिबंधित औषध',
    stop: 'थांबा',
    listen: 'ऐका',
    removeFromCompare: 'तुलनेतून काढून टाका',
    reportIssue: 'समस्येची तक्रार करा',
    bannedDrugWarning: 'प्रतिबंधित औषधाचा इशारा',
    prohibitedInIndia: 'भारतात उत्पादन आणि विक्रीसाठी प्रतिबंधित',
    bannedDrugNotice: 'गंभीर सुरक्षिततेच्या समस्या आणि आरोग्य जोखमींमुळे या औषधावर सीडीएससीओ (सेंट्रल ड्रग्ज स्टँडर्ड कंट्रोल ऑर्गनायझेशन) ने बंदी घातली आहे.',
    doNotConsume: 'या औषधाचे सेवन करू नका',
    quickSummary: 'द्रुत सारांश',
    regulatoryStatus: 'नियामक स्थिती',
    safety: 'सुरक्षा',
    verifiedInfo: 'सत्यापित माहिती',
    usesConditions: 'वापर आणि अटी',
    mechanismOfAction: 'कार्य करण्याची पद्धत',
    commonDosage: 'सामान्य डोस',
    howItWorksBody: 'शरीरात हे कसे कार्य करते',
    onsetOfAction: 'क्रियेची सुरुवात',
    durationOfEffect: 'प्रभावाचा कालावधी',
    whoShouldTake: 'कोणी घ्यावे',
    whoShouldNotTake: 'कोणी घेऊ नये',
    missedDose: 'चुकलेला डोस',
    commonSideEffects: 'सामान्य दुष्परिणाम',
    seriousSideEffects: 'गंभीर दुष्परिणाम',
    pregnancySafety: 'गर्भधारणा सुरक्षा',
    kidneyLiverWarning: 'मूत्रपिंड आणि यकृत इशारा',
    drugInteractions: 'औषधांमधील परस्पर क्रिया',
    foodInteractions: 'अन्नासह परस्पर क्रिया',
    alcoholWarning: 'मद्यपान इशारा',
    overdoseEffects: 'ओव्हरडोजचे परिणाम',
    contraindications: 'विरोधाभास',
    linkCopied: 'लिंक क्लिपबोर्डवर कॉपी केली!',
    linkCopyFailed: 'लिंक कॉपी करण्यात अयशस्वी.',
    featureComparison: 'वैशिष्ट्ये आणि प्रभावांचे side-by-side विश्लेषण',
    otc: 'ओटीसी',
    conditionNotFound: 'परिस्थिती सापडली नाही',
    conditionNotFoundDesc: "आम्हाला या परिस्थितीसाठी माहिती सापडली नाही. सामान्य लक्षण किंवा आजार शोधण्याचा प्रयत्न करा।",
    comparisonUnavailable: 'ऑफलाइन: तुलना उपलब्ध नाही',
    comparisonNotFound: 'तुलना डेटा सापडला नाही',
    comparisonOfflineDesc: "तुम्ही सध्या ऑफलाइन आहात आणि ही तुलना अद्याप जतन केलेली नाही. कृपया ही तुलना पाहण्यासाठी इंटरनेटशी कनेक्ट करा.",
    comparisonNotFoundDesc: "आम्हाला या औषधांसाठी तुलना डेटा सापडला नाही किंवा व्युत्पन्न करता आला नाही. कृपया नंतर पुन्हा प्रयत्न करा.",
  },
  ta: {
    appName: 'ஏதெல்கேர்',
    tagline: 'எந்த மருந்தையும் தேடுங்கள். உடனடியாக புரிந்து கொள்ளுங்கள்.',
    searchPlaceholder: 'மருந்து தகவலைத் தேடுங்கள்...',
    disclaimer: 'இந்த தளம் பொதுவான மருந்து தகவல்களை வழங்குகிறது. எந்தவொரு மருந்தையும் எடுத்துக்கொள்வதற்கு முன் எப்போதும் தகுதியுள்ள மருத்துவரை அணுகவும்.',
    safetyWarning: 'அறிகுறிகள் 3 நாட்களுக்கு மேல் நீடித்தால், மருத்துவரை அணுகவும்.',
    uses: 'பயன்பாடுகள்',
    howItWorks: 'இது எப்படி வேலை செய்கிறது',
    dosage: 'அளவு வழிகாட்டுதல்கள்',
    sideEffects: 'பக்க விளைவுகள்',
    overdose: 'அதிகப்படியான அளவு அபாயங்கள்',
    warnings: 'எச்சரிக்கைகள்',
    category: 'மருந்து வகை',
    popularMedicines: 'பிரபலமான மருந்துகள்',
    commonConditions: 'பொதுவான நிலைகள்',
    browseByCondition: 'மருத்துவத் தகவல்களை நிலைக்கேற்பத் தேடுங்கள்',
    quickHealthAccess: 'பொதுவான சுகாதாரத் தேவைகளுக்கான விரைவான அணுகல்',
    viewDetails: 'விவரங்களைப் பார்க்கவும்',
    noBannedFound: 'எங்கள் விரைவான தேடலில் தடைசெய்யப்பட்ட மருந்துகள் எதுவும் கிடைக்கவில்லை.',
    doloSummary: "காய்ச்சல் மற்றும் உடல் வலி நிவாரணத்திற்கு இந்தியாவின் மிகவும் நம்பிக்கைக்குரிய மருந்து.",
    augmentinSummary: "பல்வேறு பாக்டீரியா தொற்றுக்களுக்கான சக்திவாய்ந்த பிராட்-ஸ்பெக்ட்ரம் ஆண்டிபயாடிக்.",
    okacetSummary: "ஒவ்வாமை, தும்மல் மற்றும் தோல் அரிப்பு ஆகியவற்றிலிருந்து விரைவான நிவாரணம்.",
    pan40Summary: "அமிலத்தன்மை மற்றும் நெஞ்செரிச்சல் ஆகியவற்றிலிருந்து பயனுள்ள நீண்டகால நிவாரணம்.",
    suggestedFever: 'காய்ச்சல்',
    suggestedHeadache: 'தலைவலி',
    suggestedColdCough: 'சளி மற்றும் இருமல்',
    suggestedComparison: 'பாராசிட்டமால் எதிராக இப்யூபுரூஃபன்',
    doloSearchReason: 'பொதுவாக காய்ச்சல் மேலாண்மைக்காக தேடப்படுகிறது',
    ibuprofenSearchReason: 'வலி நிவாரணத்திற்கு முக்கியமான பாதுகாப்பு தகவல்',
    dryCoughSearchReason: 'பருவகால நோய் தொடர்பான கேள்வி',
    throatInfectionSearchReason: 'அடிக்கடி ஏற்படும் பாக்டீரியா தொற்று தொடர்பான கேள்வி',
    diabetesSearchReason: 'நீரிழிவு மேலாண்மைக்காக அதிகம் தேடப்படுகிறது',
    amlodipineSearchReason: 'பொதுவான இரத்த அழுத்த மருந்து தொடர்பான கேள்வி',
    loading: 'தகவலைப் பெறுகிறது...',
    category_analgesic: 'வலி நிவாரணி',
    category_antibiotic: 'ஆண்டிபயாடிக்',
    category_antihistamine: 'ஆண்டிகிஸ்டமைன்',
    category_antacid: 'ஆன்டாசிட்',
    scannerTitle: 'AI சுகாதார ஸ்கேனர்',
    scannerSubtitle: 'உடனடி பகுப்பாய்விற்கு மருந்துகள், மருத்துவரின் பரிந்துரைகள் அல்லது ஆய்வக அறிக்கைகளை ஸ்கேன் செய்யுங்கள்.',
    medicineMode: 'மருந்து',
    prescriptionMode: 'மருந்துச் சீட்டு',
    reportMode: 'ஆய்வக அறிக்கை',
    takePhoto: 'புகைப்படம் எடு',
    uploadImage: 'படத்தைப் பதிவேற்று',
    analyzingMedication: 'மருந்தை பகுப்பாய்வு செய்கிறது...',
    readingPrescription: 'மருந்துச் சீட்டைப் படிக்கிறது...',
    analyzingReport: 'ஆய்வக அறிக்கையை பகுப்பாய்வு செய்கிறது...',
    scannerTips: 'ஸ்கேனிங் குறிப்புகள்',
    scannerTip1: 'உரை தெளிவாகத் தெரிவதையும் கவனத்தில் இருப்பதையும் உறுதிப்படுத்தவும்',
    scannerTip2: 'காகிதம்/பேக்கேஜிங்கில் பிரதிபலிப்பைத் தவிர்க்கவும்',
    scannerTip3: 'கேமராவை நிலையாகப் பிடித்து நல்ல வெளிச்சத்தைப் பயன்படுத்தவும்',
    scannerTip4: 'முழு ஆவணமும் பிரேமிற்குள் இருப்பதை உறுதி செய்யவும்',
    scannerTip5: 'கையெழுத்துக் குறிப்புகளுக்கு, அவை தெளிவாக இருப்பதை உறுதி செய்யவும்',
    confidence: 'நம்பிக்கை',
    verified: 'சரிபார்க்கப்பட்டது',
    viewFullDetails: 'முழு விவரங்களையும் பார்க்கவும்',
    prescriptionDetails: 'மருந்துச் சீட்டு விவரங்கள்',
    doctorNotes: "மருத்துவரின் குறிப்புகள்",
    abnormalFindings: 'அசாதாரண கண்டுபிடிப்புகள்',
    noAbnormalFindings: 'இந்த அறிக்கையில் அசாதாரண கண்டுபிடிப்புகள் எதுவும் கண்டறியப்படவில்லை.',
    timetableTitle: 'எனது கால அட்டவணை',
    timetableSubtitle: 'உங்கள் தினசரி மருந்து அட்டவணையை நிர்வகிக்கவும்',
    notificationsActive: 'அறிவிப்புகள் செயலில் உள்ளன',
    addMed: 'மருந்தைச் சேர்',
    saveSchedule: 'அட்டவணையைச் சேமி',
    cancel: 'ரத்துசெய்',
    medicineName: 'மருந்தின் பெயர்',
    medicineSearchPlaceholder: 'தேடுங்கள் அல்லது பெயரை உள்ளிடவும்...',
    dosageLabel: 'அளவு',
    dosagePlaceholder: 'உதாரணமாக 1 மாத்திரை',
    timeLabel: 'நேரம்',
    frequencyLabel: 'அதிர்வெண்',
    todaysDoses: "இன்றைய அளவுகள்",
    otherDays: 'மற்ற நாட்கள்',
    timetableEmpty: 'உங்கள் கால அட்டவணை காலியாக உள்ளது',
    timetableEmptyDesc: 'தொடர்ந்து கண்காணிக்க உங்கள் முதல் மருந்தைச் சேர்க்கவும்.',
    markAsTaken: 'எடுக்கப்பட்டது என குறிக்கவும்',
    taken: 'எடுக்கப்பட்டது',
    bannedWarning: 'இந்தியாவில் தடைசெய்யப்பட்ட மருந்து. உடனடியாக மருத்துவரை அணுகவும்.',
    tip1: 'உங்கள் மருந்துடன் ஒரு கிளாஸ் தண்ணீர் குடிக்கவும்.',
    tip2: 'ஒவ்வொரு நாளும் ஒரே நேரத்தில் மருந்து எடுத்துக் கொள்ளுங்கள்.',
    tip3: "சிறந்த செயல்திறனுக்காக மருந்தைத் தவிர்க்க வேண்டாம்.",
    tip4: 'மருந்துகளை குளிர்ந்த, உலர்ந்த இடத்தில் வைக்கவும்.',
    tip5: 'எடுத்துக்கொள்வதற்கு முன் காலாவதி தேதியைச் சரிபார்க்கவும்.',
    tip6: 'அறிவுறுத்தப்படாவிட்டால் பழச்சாறுகளுடன் மருந்து எடுப்பதைத் தவிர்க்கவும்.',
    noResults: 'மருந்துகள் எதுவும் கிடைக்கவில்லை.',
    timetable_timing: 'நேரம்',
    timetable_duration: 'காலம்',
    timetable_purpose: 'நோக்கம்',
    backOnline: 'மீண்டும் ஆன்லைனில்!',
    allFeaturesAvailable: 'அனைத்து அம்சங்களும் இப்போது கிடைக்கின்றன.',
    footerCopyright: 'ஏதெல்கேர். அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
    privacyPolicy: 'தனியுரிமைக் கொள்கை',
    cdscoOfficial: 'CDSCO அதிகாரப்பூர்வ',
    educationalDisclaimer: 'கல்வி நோக்கங்களுக்காக மட்டுமே. தொழில்முறை மருத்துவ ஆலோசனைக்கு மாற்றாகாது.',
    installTitle: 'ஏதெல்கேர் நிறுவவும்',
    installOffline: 'எங்கும் ஆஃப்லைன் அணுகல்',
    installFaster: 'வேகமான லோடிங் நேரங்கள்',
    installNow: 'இப்போதே நிறுவவும்',
    enableNotificationsPrompt: 'மருந்து நினைவூட்டல்களைப் பெற அறிவிப்புகளை இயக்கவும்!',
    notificationsNotSupported: 'இந்த உலாவியில் அறிவிப்புகள் ஆதரிக்கப்படவில்லை',
    notificationsBlocked: 'அறிவிப்புகள் தடுக்கப்பட்டுள்ளன. உங்கள் உலாவி அமைப்புகளில் அவற்றை இயக்கவும்.',
    notificationsEnabled: 'அறிவிப்புகள் இயக்கப்பட்டன!',
    notificationsReadyDesc: 'இனி நீங்கள் சரியான நேரத்தில் மருந்து நினைவூட்டல்களையும் சுகாதாரக் குறிப்புகளையும் பெறுவீர்கள்.',
    enableNotifications: 'அறிவிப்புகளை இயக்கவும்',
    timetableLoadError: 'கால அட்டவணையை ஏற்ற முடியவில்லை.',
    scheduleAdded: 'அட்டவணை வெற்றிகரமாகச் சேர்க்கப்பட்டது',
    scheduleAddError: 'அட்டவணையைச் சேர்ப்பதில் தோல்வி',
    scheduleRemoved: 'அட்டவணை நீக்கப்பட்டது',
    scheduleRemoveError: 'அட்டவணையை நீக்குவதில் தோல்வி',
    markedNotTaken: 'எடுக்கப்படவில்லை என குறிக்கப்பட்டது',
    markedTaken: 'எடுக்கப்பட்டது என குறிக்கப்பட்டது! நன்று.',
    statusUpdateError: 'நிலையைப் புதுப்பிப்பதில் தோல்வி',
    timeFor: 'நேரம் வந்துவிட்டது',
    snooze: 'ஸ்னூஸ்',
    enabled: 'இயக்கப்பட்டது',
    day_mon: 'திங்கள்',
    day_tue: 'செவ்வாய்',
    day_wed: 'புதன்',
    day_thu: 'வியாழன்',
    day_fri: 'வெள்ளி',
    day_sat: 'சனி',
    day_sun: 'ஞாயிறு',
    noMedicationFound: 'இந்தப் படத்தில் மருந்தைக் கண்டறிய முடியவில்லை. தெளிவான படத்துடன் மீண்டும் முயற்சிக்கவும்.',
    noPrescriptionFound: 'மருந்துச் சீட்டு விவரங்களைப் பெற முடியவில்லை. படம் தெளிவாக இருப்பதையும், அதில் சரியான மருந்துச் சீட்டு இருப்பதையும் உறுதிப்படுத்தவும்.',
    noReportFound: 'ஆய்வக அறிக்கை விவரங்களைப் பெற முடியவில்லை. படம் தெளிவாக இருப்பதையும், அதில் சரியான அறிக்கையையும் இருப்பதை உறுதி செய்யவும்.',
    scanningFailed: 'ஸ்கேன் செய்வது தோல்வியடைந்தது',
    tryAgain: 'மீண்டும் முயற்சிக்கவும்',
    lowConfidenceWarn: 'அடையாளம் காண்பதில் குறைந்த நம்பிக்கை. இந்தப் படம் படிக்க மிகவும் கடினமாக உள்ளது. சிறந்த ஒளி அல்லது தெளிவான கோணத்தில் மீண்டும் முயற்சிக்கவும்.',
    uncertainIdentification: 'படத்தின் தரம் காரணமாக அடையாளம் காண்பது நிச்சயமற்றது. தயாரிப்பு பேக்கேஜிங் மூலம் சரிபார்க்கவும்.',
    result: 'முடிவு',
    normal: 'சாதாரண',
    addedToCompare: 'ஒப்பீட்டில் சேர்க்கப்பட்டது',
    removedFromCompare: 'ஒப்பீட்டிலிருந்து நீக்கப்பட்டது',
    singleLineSummary: 'சுருக்கம்',
    compare: 'ஒப்பிடு',
    myDashboard: 'எனது டாஷ்போர்டு',
    dashboardDesc: 'உங்கள் கணக்கு, செயலில் உள்ள திட்டங்கள் மற்றும் கட்டண வரலாற்றை நிர்வகிக்கவும்.',
    profile: 'சுயவிவரம்',
    role: 'பங்கு',
    joined: 'சேர்ந்தார்',
    currentPlan: 'தற்போதைய திட்டம்',
    active: 'செயலில் உள்ளது',
    expired: 'காலாவதியானது',
    freeTier: 'இலவச அடுக்கு',
    validUntil: 'வரை செல்லுபடியாகும்',
    daysRemaining: 'மீதமுள்ள நாட்கள்',
    days: 'நாட்கள்',
    changePlan: 'திட்டத்தை மாற்றவும்',
    subscriptionExpired: 'உங்கள் சந்தா காலாவதியாகிவிட்டது',
    subscriptionExpiredDesc: 'உங்கள் முந்தைய {tier} திட்டம் {date} அன்று காலாவதியானது. வரம்பற்ற AI சுகாதார ஸ்கேனிங் மற்றும் முன்னுரிமை ஆதரவை மீண்டும் பெற இப்போது புதுப்பிக்கவும்.',
    renewSubscription: 'சந்தாவை புதுப்பிக்கவும்',
    noActiveSubscription: 'செயலில் உள்ள சந்தா இல்லை',
    noActiveSubscriptionDesc: 'வரம்பற்ற AI சுகாதார ஸ்கேனிங், பரிந்துரை பகுப்பாய்வு மற்றும் ஆய்வக அறிக்கை நுண்ணறிவுகளைப் பெற பிரீமியத்திற்கு மேம்படுத்தவும்.',
    upgradeToPremium: 'பிரீமியத்திற்கு மேம்படுத்தவும்',
    paymentHistory: 'கட்டண வரலாறு',
    loadingHistory: 'கட்டண வரலாறு ஏற்றப்படுகிறது...',
    date: 'தேதி',
    amount: 'தொகை',
    status: 'நிலை',
    transactionId: 'பரிவர்த்தனை ஐடி',
    noPayments: 'இன்னும் கட்டணங்கள் இல்லை',
    noPaymentsDesc: 'நீங்கள் சந்தா செலுத்தியவுடன் உங்கள் கட்டண வரலாறு இங்கே தோன்றும்.',
    unlockAIScanner: 'AI ஹெல்த் ஸ்கேனரைத் திறக்கவும்',
    chooseAPlan: 'வரம்பற்ற ஸ்கேனிங் அம்சங்களை அணுக ஒரு திட்டத்தைத் தேர்ந்தெடுக்கவும்',
    mostPopular: 'மிகவும் பிரபலமானது',
    oneTimePass: 'ஒருமுறை கடப்பு',
    day: 'நாள்',
    monthlyPro: 'மாதாந்திர புரோ',
    month: 'மாதம்',
    yearlyPremium: 'வருடாந்திர பிரீமியம்',
    year: 'ஆண்டு',
    breakdown: 'கட்டண விவரம்',
    platformFee: 'பிளாட்பார்ம் கட்டணம்',
    gst: 'ஜிஎஸ்டி',
    totalAmount: 'மொத்த தொகை',
    paySecurely: '₹{total} பாதுகாப்பாக செலுத்துங்கள்',
    processing: 'செயலாக்கப்படுகின்றது...',
    securedByRazorpay: 'ரேசர்பே மூலம் பாதுகாக்கப்பட்டது',
    oneTimePassDesc: '24 மணிநேர வரம்பற்ற ஸ்கேனிங்',
    monthlyProDesc: 'வழக்கமான சுகாதார கண்காணிப்புக்கு ஏற்றது',
    yearlyPremiumDesc: 'நீண்ட கால பராமரிப்புக்கான சிறந்த மதிப்பு',
    unlimitedScanning: 'வரம்பற்ற AI ஸ்கேனிங்',
    prescriptionAnalysis: 'பரிந்துரை பகுப்பாய்வு',
    labReportAnalysis: 'ஆய்வக அறிக்கை பகுப்பாய்வு',
    valid24Hours: '24 மணிநேரத்திற்கு செல்லுபடியாகும்',
    prioritySupport: 'முன்னுரிமை ஆதரவு',
    earlyAccess: 'அம்சங்களுக்கான ஆரம்ப அணுகல்',
    bannedDrugsRegistry: 'தடைசெய்யப்பட்ட மருந்துகளின் பதிவேடு',
    officialCDSCOData: 'அதிகாரப்பூர்வ CDSCO தரவு',
    bannedDrugsDesc: 'மருந்துகள் மற்றும் அழகுசாதனப் பொருட்கள் சட்டம், 1940 இன் பிரிவு 26A இன் கீழ் இந்தியாவில் உற்பத்தி மற்றும் விற்பனைக்குத் தடைசெய்யப்பட்ட மருந்துகளின் விரிவான பட்டியல்।',
    searchBannedPlaceholderLong: 'பெயர் அல்லது பக்கவிளைவு மூலம் தடைசெய்யப்பட்ட மருந்துகளைத் தேடுங்கள்...',
    primaryRisk: 'முதன்மை ஆபத்து',
    noBannedFoundTitle: 'தடைசெய்யப்பட்ட மருந்துகள் எதுவும் காணப்படவில்லை',
    noBannedFoundDesc: 'உங்கள் தேடல் சொற்களைச் சரிசெய்து முயற்சிக்கவும்।',
    vs: 'எதிராக',
    feature: 'அம்சம்',
    difference: 'வேறுபாடு',
    peopleAlsoSearch: 'மக்கள் இதையும் தேடுகிறார்கள்',
    suggestedQueries: 'பரிந்துரைக்கப்பட்ட தேடல்கள்',
    voiceSearch: 'குரல் தேடல்',
    listening: 'கேட்கிறது...',
    offlineTitle: 'நீங்கள் ஆஃப்லைனில் உள்ளீர்கள்',
    offlineStatus: 'சேமிக்கப்பட்ட தரவு மட்டுமே காட்டப்படுகிறது',
    offlineLimit: 'AI-இயங்கும் தேடல் மற்றும் டைனாமிக் விவரங்கள் வரையறுக்கப்பட்டுள்ளன.',
    offlineAction: 'அனைத்து அம்சங்களையும் மீண்டும் செயல்படுத்த, நீங்கள் ஆன்லைனில் வந்ததும் பக்கத்தைப் புதுப்பிக்கவும்.',
    refresh: 'புதுப்பி',
    fever: 'காய்ச்சல்',
    cold: 'சளி மற்றும் இருமல்',
    headache: 'தலைவலி',
    diabetes: 'நீரிழிவு நோய்',
    hypertension: 'உயர் இரத்த அதிகம்',
    acidity: 'அசிடிட்டி',
    allergies: 'ஒவ்வாமை',
    infections: 'தொற்று',
    asthma: 'ஆஸ்துமா',
    joint_pain: 'மூட்டு வலி',
    skin_issues: 'சரும பிரச்சனைகள்',
    eye_strain: 'கண் சோர்வு',
    fatigue: 'சோர்வு',
    heart_health: 'இதய ஆரோக்கியம்',
    stomach_flu: 'வயிற்று காய்ச்சல்',
    back_pain: 'முதுகு வலி',
    migraine: 'ஒற்றைத் தலைவலி',
    thyroid: 'தைராய்டு',
    anxiety: 'கவலை',
    sleep_disturbances: 'தூக்கப் பிரச்சினைகள்',
    viewAll: 'அனைத்தையும் காண்க',
    share: 'பகிர்',
    medicalIntelligence: 'இந்தியாவின் மருத்துவ நுண்ணறிவு',
    privacyFirst: 'தனியுரிமை முதலில்',
    healthDecoded: 'உங்கள் ஆரோக்கியம்,',
    decoded: 'விளக்கப்பட்டது.',
    heroDescription: 'இந்தியாவிற்கான மிகவும் நம்பகமான, தனியுரிமை-மையப்படுத்தப்பட்ட மருந்து நுண்ணறிவு தளம்.',
    diagnosticVision: 'AI கண்டறியும் பார்வை',
    diagnosticVisionDesc: 'தனியுரிம நரம்பியல் ஸ்கேனிங் மூலம் மருந்துகளை அடையாளம் கண்டு சிக்கலான மருத்துவ அறிக்கைகளை பகுப்பாய்வு செய்யுங்கள்.',
    neuralReminders: 'நரம்பியல் நினைவூட்டல்கள்',
    neuralRemindersDesc: 'தொடர்ச்சியான குறுக்கு-தள விழிப்பூட்டல்களுடன் உங்கள் டோஸ் சுழற்சிகளுக்கான ஸ்மார்ட் ஒத்திசைவு.',
    smartComparison: 'ஸ்மார்ட் ஒப்பீடு',
    smartComparisonDesc: 'உப்புகள், பக்க விளைவுகள் மற்றும் பலவற்றின் பக்கவாட்டு பகுப்பாய்வு.',
    cdscoAlert: 'CDSCO எச்சரிக்கை',
    bannedDrugsSearch: 'தடைசெய்யப்பட்ட மருந்துகள் தேடல்',
    bannedDrugsSearchDesc: 'இந்தியாவில் ஒரு மருந்து உற்பத்தி மற்றும் விற்பனைக்கு தடை செய்யப்பட்டுள்ளதா என்பதை விரைவாகச் சரிபார்க்கவும்.',
    fullRegistry: 'முழு பதிவேடு',
    medicalDisclaimer: 'மருத்துவ மறுப்பு',
    launchScanner: 'ஸ்கேனரைத் தொடங்கு',
    authRequired: 'அங்கீகாரம் தேவை',
    configureCycles: 'சுழற்சிகளை உள்ளமைக்கவும்',
    readWhy: 'ஏன் என்று படிக்கவும்',
    peopleAlsoSearchDesc: 'தற்போதைய சுகாதார போக்குகள் மற்றும் CDSCO வழிகாட்டுதல்களின் அடிப்படையில்',
    timetable: 'கால அட்டவணை',
    scan: 'ஸ்கேன்',
    dashboard: 'டாஷ்போர்டு',
    adminPanel: 'நிர்வாக குழு',
    signOut: 'வெளியேறு',
    signIn: 'உள்நுழைக',
    cdscoVerified: 'CDSCO சரிபார்க்கப்பட்டது',
    searchBannedPlaceholder: 'தடைசெய்யப்பட்ட மருந்து பெயரைத் தேடுங்கள்...',
    analyzingMedicine: 'மருந்து பகுப்பாய்வு செய்யப்படுகிறது',
    gatheringData: 'விரிவான தரவு, பக்க விளைவுகள் மற்றும் பாதுகாப்புத் தகவல்கள் சேகரிக்கப்படுகின்றன...',
    medicineNotFound: 'மருந்து கிடைக்கவில்லை',
    medicineNotFoundDesc: '"{name}" க்கான தகவலை எங்களால் கண்டுபிடிக்க முடியவில்லை. பொதுவான பெயர் அல்லது பிரபலமான பிராண்டைத் தேட முயற்சிக்கவும்.',
    backToHome: 'முகப்புக்குத் திரும்பு',
    backToSearch: 'தேடலுக்குத் திரும்பு',
    viewingOfflineData: 'ஆஃப்லைன் தரவைப் பார்க்கிறீர்கள்',
    source: 'ஆதாரம்',
    prescriptionRequired: 'மருந்து சீட்டு தேவை',
    otcNonPrescription: 'OTC / சீட்டு தேவையில்லை',
    bannedDrug: 'தடைசெய்யப்பட்ட மருந்து',
    stop: 'நிறுத்து',
    listen: 'கேள்',
    removeFromCompare: 'ஒப்பீட்டிலிருந்து நீக்கு',
    reportIssue: 'சிக்கலைப் புகாரளி',
    bannedDrugWarning: 'தடைசெய்யப்பட்ட மருந்து எச்சரிக்கை',
    prohibitedInIndia: 'இந்தியாவில் உற்பத்தி மற்றும் விற்பனைக்குத் தடை செய்யப்பட்டது',
    bannedDrugNotice: 'தீவிர பாதுகாப்பு கவலைகள் மற்றும் சுகாதார அபாயங்கள் காரணமாக இந்த மருந்து CDSCO (மத்திய மருந்துகள் தரக் கட்டுப்பாட்டு நிறுவனம்) ஆல் தடை செய்யப்பட்டுள்ளது.',
    doNotConsume: 'இந்த மருந்தை உட்கொள்ள வேண்டாம்',
    quickSummary: 'விரைவான சுருக்கம்',
    regulatoryStatus: 'ஒழுங்குமுறை நிலை',
    safety: 'பாதுகாப்பு',
    verifiedInfo: 'சரிபார்க்கப்பட்ட தகவல்',
    usesConditions: 'பயன்பாடுகள் மற்றும் நிலைகள்',
    mechanismOfAction: 'செயல்பாட்டு முறை',
    commonDosage: 'பொதுவான அளவு',
    howItWorksBody: 'உடலில் இது எப்படி வேலை செய்கிறது',
    onsetOfAction: 'செயல்பாட்டின் ஆரம்பம்',
    durationOfEffect: 'விளைவின் காலம்',
    whoShouldTake: 'யார் எடுத்துக் கொள்ள வேண்டும்',
    whoShouldNotTake: 'யார் எடுத்துக் கொள்ளக் கூடாது',
    missedDose: 'தவறிய அளவு',
    commonSideEffects: 'பொதுவான பக்க விளைவுகள்',
    seriousSideEffects: 'தீவிரமான பக்க விளைவுகள்',
    pregnancySafety: 'கர்ப்ப கால பாதுகாப்பு',
    kidneyLiverWarning: 'சிறுநீரகம் மற்றும் கல்லீரல் எச்சரிக்கை',
    drugInteractions: 'மருந்து இடைவினைகள்',
    foodInteractions: 'உணவு இடைவினைகள்',
    alcoholWarning: 'மது எச்சரிக்கை',
    overdoseEffects: 'அதிகப்படியான அளவின் விளைவுகள்',
    contraindications: 'முரண்பாடுகள்',
    linkCopied: 'இணைப்பு நகலெடுக்கப்பட்டது!',
    linkCopyFailed: 'இணைப்பை நகலெடுத்தலில் தோல்வி.',
    featureComparison: 'அம்சங்கள் மற்றும் விளைவுகளின் பக்கவாட்டு ஒப்பீடு',
    otc: 'OTC',
    conditionNotFound: 'நிலை காணப்படவிலை',
    conditionNotFoundDesc: "இந்த நிலைக்கான தகவலை எங்களால் கண்டுபிடிக்க முடியவில்லை. பொதுவான அறிகுறி அல்லது நோயைத் தேட முயற்சிக்கவும்.",
    comparisonUnavailable: 'ஆஃப்லைன்: ஒப்பீடு கிடைக்கவில்லை',
    comparisonNotFound: 'ஒப்பீட்டுத் தரவு கிடைக்கவில்லை',
    comparisonOfflineDesc: "நீங்கள் தற்போது ஆஃப்லைனில் உள்ளீர்கள், இந்த ஒப்பீடு இன்னும் சேமிக்கப்படவில்லை. இந்த ஒப்பீட்டைப் பார்க்க இணையத்துடன் இணைக்கவும்.",
    comparisonNotFoundDesc: "இந்த மருந்துகளுக்கான ஒப்பீட்டுத் தரவை எங்களால் கண்டுபிடிக்க முடியவில்லை அல்லது உருவாக்க முடியவில்லை. பிறகு முயற்சிக்கவும்.",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('medinfo_lang');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('medinfo_lang', language);
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
